### ISSUE TITLE
Dell Latitude 5411

### ISSUE THREAD

**Issue by franklin-gedler** [blankmac/AlpsHID#6]
Hello, the trackpad model is Dell09C0. I tried with the kexts of this repository and I still can't get it to work correctly, is there any way to make it work? Thank you

**Comment by juico** [comment]
Hey, it seems the issue is similar to with the [dell 5500](https://github.com/blankmac/AlpsHID/issues/4), it uses the cirque vendor id instead of the alps, you can try this: https://github.com/blankmac/AlpsHID/files/7359646/AlpsHID_5500.zip . I should add these changes to a new release but you can try the AlpsHID_5500 zip and report back if it works for you.

**Comment by franklin-gedler** [comment]
@juico Thank you very much, with the kexts that you gave me now I keep the physical buttons running, the touchpad accepts the MacOS gestures, the only detail that I observed is that the touchpad click does not work, would you have any way to make it work?

**Comment by juico** [comment]
Nice that it works for you, I am not sure about the the touchpad click you are talking about. Does the touchpad have a physical click when you press it? You can also enable the "Tap to click" option in the Trackpad control panel. 

If you do have a clicking touchpad i can take a look to get it working although i am a bit busy at the moment. In two weeks i should have some more time to look at it.

**Comment by franklin-gedler** [comment]
@juico 
Thank you very much, I am fully working now.
